---
- name: Remove Apache2 and PHP support on all hosts
  hosts: all
  become: true
  tasks:
    - name: Update repository index
      ansible.builtin.apt:
        update_cache: yes

    - name: Remove Apache2 package
      ansible.builtin.apt:
        name: apache2
        state: absent

    - name: Remove support for PHP
      ansible.builtin.apt:
        name: libapache2-mod-php
        state: absent
